# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c474dc99a219fbb4414946602e0ff2f02e63f9c56c6c5add387cbe4655ab253146be13b24879f85da7e914a2dbdc0a82a276ea4115b33a5e1821504abc1df6

test:
  secret_key_base: ac0ead6f73a72197c4b6740da6868f130389f9abe5e2a9482489ac37517e84d868fe19322e735ea9eec8443b337a46a34af9a40d5def3f023c4e288144a234f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
